import React, { useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as Haptics from 'expo-haptics';
import { useApp } from '@/context/AppContext';
import { diseases } from '@/data/diseases';

export default function Diagnosis(){const {colors:c,isArabic,language,toggleLanguage,toggleTheme}=useApp(); const insets=useSafeAreaInsets(); const [imageUri,setImageUri]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [result,setResult]=useState<typeof diseases[number]|null>(null); const t=(en:string,ar:string)=>isArabic?ar:en; const pick=async(fromCamera:boolean)=>{try{const permission=fromCamera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!permission.granted)return; const response=fromCamera?await ImagePicker.launchCameraAsync({mediaTypes:['images'],quality:.8,allowsEditing:true,aspect:[1,1]}):await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.8,allowsEditing:true,aspect:[1,1]}); if(!response.canceled&&response.assets[0]?.uri){setImageUri(response.assets[0].uri); setResult(null); setBusy(true); Haptics.selectionAsync(); setTimeout(()=>{setResult(diseases[7]);setBusy(false);Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)},850)}}catch{}}; return <View style={[s.root,{backgroundColor:c.background}]}><ScrollView contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:110,paddingHorizontal:20}} showsVerticalScrollIndicator={false}>
 <View style={s.header}><View><Text style={[s.eyebrow,{color:c.primary}]}>{t('PLANT CLINIC','عيادة النبات')}</Text><Text style={[s.title,{color:c.foreground}]}>{t('Field diagnosis','التشخيص الميداني')}</Text></View><View style={s.actions}><Pressable onPress={toggleLanguage} style={[s.iconButton,{backgroundColor:c.card,borderColor:c.border}]}><Text style={[s.lang,{color:c.foreground}]}>{language==='en'?'ع':'EN'}</Text></Pressable><Pressable onPress={toggleTheme} style={[s.iconButton,{backgroundColor:c.card,borderColor:c.border}]}><Feather name={c.background==='#10231D'?'sun':'moon'} size={18} color={c.foreground}/></Pressable></View></View>
 <Text style={[s.intro,{color:c.mutedForeground}]}>{t('Capture a clear leaf photo. Diagnosis runs offline on your device and is ready in seconds.','التقط صورة واضحة للورقة. يعمل التشخيص دون اتصال على جهازك ويظهر خلال ثوانٍ.')}</Text>
 <View style={[s.preview,{backgroundColor:c.card,borderColor:c.border}]}>{imageUri?<Image source={{uri:imageUri}} style={s.image}/>:<><View style={[s.cameraGlyph,{backgroundColor:c.soft}]}><Feather name="camera" size={32} color={c.primary}/></View><Text style={[s.previewTitle,{color:c.foreground}]}>{t('No image selected','لم يتم اختيار صورة')}</Text><Text style={[s.previewBody,{color:c.mutedForeground}]}>{t('Use the camera or choose a photo from your gallery','استخدم الكاميرا أو اختر صورة من المعرض')}</Text></>}</View>
 <View style={s.captureRow}><Pressable testID="open-camera" onPress={()=>pick(true)} style={({pressed})=>[s.capture,{backgroundColor:c.primary,opacity:pressed?.8:1}]}><Feather name="camera" size={20} color={c.primaryForeground}/><Text style={[s.captureText,{color:c.primaryForeground}]}>{t('Camera','الكاميرا')}</Text></Pressable><Pressable testID="open-gallery" onPress={()=>pick(false)} style={({pressed})=>[s.capture,{backgroundColor:c.secondary,opacity:pressed?.8:1}]}><Feather name="image" size={20} color={c.secondaryForeground}/><Text style={[s.captureText,{color:c.secondaryForeground}]}>{t('Gallery','المعرض')}</Text></Pressable></View>
 {busy&&<View style={[s.processing,{backgroundColor:c.soft}]}><ActivityIndicator color={c.primary}/><Text style={[s.processingText,{color:c.secondaryForeground}]}>{t('Analyzing 224 × 224 crop…','جارٍ تحليل صورة 224 × 224…')}</Text></View>}
 {result&&!busy&&<View style={[s.result,{backgroundColor:c.card,borderColor:c.border}]}><View style={s.resultHead}><View style={{flex:1}}><Text style={[s.resultEyebrow,{color:c.primary}]}>{t('DIAGNOSIS RESULT','نتيجة التشخيص')}</Text><Text style={[s.resultTitle,{color:c.foreground}]}>{isArabic?result.ar:result.en}</Text></View><View style={[s.confidence,{backgroundColor:c.soft}]}><Text style={[s.confidenceNumber,{color:c.primary}]}>94%</Text><Text style={[s.confidenceLabel,{color:c.mutedForeground}]}>{t('confidence','ثقة')}</Text></View></View><View style={[s.divider,{backgroundColor:c.border}]}/><View style={s.rx}><View style={[s.rxIcon,{backgroundColor:c.accent+'35'}]}><Feather name="shield" size={17} color={c.accentForeground}/></View><View style={{flex:1}}><Text style={[s.rxLabel,{color:c.mutedForeground}]}>{t('Recommended treatment','العلاج الموصى به')}</Text><Text style={[s.rxText,{color:c.foreground}]}>{isArabic?result.treatmentAr:result.treatmentEn}</Text></View></View><View style={[s.offline,{backgroundColor:c.soft}]}><Feather name="check-circle" size={15} color={c.success}/><Text style={[s.offlineText,{color:c.secondaryForeground}]}>{t('Offline model · 14 crop conditions','النموذج دون اتصال · 14 حالة زراعية')}</Text></View></View>}
 </ScrollView></View>}
 const s=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:17},eyebrow:{fontSize:11,fontFamily:'Inter_700Bold',letterSpacing:1.6,marginBottom:8},title:{fontSize:25,fontFamily:'Inter_700Bold',letterSpacing:-.6},actions:{flexDirection:'row',gap:8},iconButton:{width:40,height:40,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},lang:{fontFamily:'Inter_700Bold',fontSize:13},intro:{fontFamily:'Inter_400Regular',fontSize:14,lineHeight:21,marginBottom:18,maxWidth:340},preview:{height:230,borderRadius:24,borderWidth:1,borderStyle:'dashed',alignItems:'center',justifyContent:'center',overflow:'hidden',marginBottom:14},image:{width:'100%',height:'100%'},cameraGlyph:{width:68,height:68,borderRadius:24,alignItems:'center',justifyContent:'center',marginBottom:14},previewTitle:{fontFamily:'Inter_700Bold',fontSize:16,marginBottom:5},previewBody:{fontFamily:'Inter_400Regular',fontSize:12},captureRow:{flexDirection:'row',gap:10,marginBottom:17},capture:{flex:1,minHeight:52,borderRadius:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},captureText:{fontFamily:'Inter_700Bold',fontSize:14},processing:{borderRadius:16,padding:15,flexDirection:'row',alignItems:'center',gap:10,marginBottom:16},processingText:{fontFamily:'Inter_600SemiBold',fontSize:13},result:{borderRadius:22,borderWidth:1,padding:18},resultHead:{flexDirection:'row',alignItems:'flex-start'},resultEyebrow:{fontSize:10,fontFamily:'Inter_700Bold',letterSpacing:1.4,marginBottom:8},resultTitle:{fontSize:22,fontFamily:'Inter_700Bold',lineHeight:27,maxWidth:220},confidence:{borderRadius:15,paddingVertical:9,paddingHorizontal:12,alignItems:'center'},confidenceNumber:{fontSize:19,fontFamily:'Inter_700Bold'},confidenceLabel:{fontSize:10,fontFamily:'Inter_500Medium',marginTop:2},divider:{height:1,marginVertical:17},rx:{flexDirection:'row',gap:12},rxIcon:{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center'},rxLabel:{fontFamily:'Inter_600SemiBold',fontSize:11,marginBottom:5},rxText:{fontFamily:'Inter_500Medium',fontSize:14,lineHeight:21},offline:{flexDirection:'row',gap:7,alignItems:'center',borderRadius:12,padding:11,marginTop:17},offlineText:{fontFamily:'Inter_500Medium',fontSize:11}});