import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { useApp } from '@/context/AppContext';

export default function FieldHealth(){const {colors:c,isArabic,language,toggleLanguage,toggleTheme}=useApp(); const insets=useSafeAreaInsets(); const router=useRouter(); const t=(en:string,ar:string)=>isArabic?ar:en; const sectors=[['A-1','0.61','Healthy','healthy'],['A-2','0.48','Healthy','healthy'],['A-3','0.36','Warning','warning'],['A-4','0.18','Danger zone','danger']]; return <View style={[s.root,{backgroundColor:c.background,direction:isArabic?'rtl':'ltr'}]}><ScrollView contentContainerStyle={{paddingTop:insets.top+12,paddingBottom:110,paddingHorizontal:20}} showsVerticalScrollIndicator={false}>
 <View style={s.header}><View><Text style={[s.eyebrow,{color:c.primary}]}>{t('FIELD INTELLIGENCE','ذكاء الحقل')}</Text><Text style={[s.title,{color:c.foreground}]}>{t('Good morning, farmer','صباح الخير، أيها المزارع')}</Text></View><View style={s.actions}><Pressable onPress={toggleLanguage} style={[s.iconButton,{backgroundColor:c.card,borderColor:c.border}]}><Text style={[s.lang,{color:c.foreground}]}>{language==='en'?'ع':'EN'}</Text></Pressable><Pressable onPress={toggleTheme} style={[s.iconButton,{backgroundColor:c.card,borderColor:c.border}]}><Feather name={c.background==='#10231D'?'sun':'moon'} size={18} color={c.foreground}/></Pressable></View></View>
 <View style={[s.hero,{backgroundColor:c.primary}]}><View><Text style={s.heroLabel}>{t('FIELD HEALTH INDEX','مؤشر صحة الحقل')}</Text><Text style={s.heroNumber}>0.32</Text><Text style={s.heroCaption}>{t('Water / biotic stress','إجهاد مائي / حيوي')}</Text></View><View style={s.ring}><Text style={s.ringText}>NDVI</Text><Text style={s.ringSub}>{t('Moderate','متوسط')}</Text></View></View>
 <View style={s.sectionHead}><Text style={[s.sectionTitle,{color:c.foreground}]}>{t('Live sectors','القطاعات المباشرة')}</Text><Text style={[s.updated,{color:c.mutedForeground}]}>{t('Updated 8 min ago','آخر تحديث منذ 8 دقائق')}</Text></View>
 <View style={s.grid}>{sectors.map(([name,value,status,tone])=><View key={name} style={[s.sector,{backgroundColor:c.card,borderColor:c.border}]}><View style={s.sectorTop}><Text style={[s.sectorName,{color:c.foreground}]}>{t('Sector ','القطاع ')}{name}</Text><View style={[s.dot,{backgroundColor:tone==='healthy'?c.success:tone==='warning'?c.warning:c.danger}]} /></View><Text style={[s.ndvi,{color:c.foreground}]}>{value}</Text><Text style={[s.status,{color:tone==='healthy'?c.success:tone==='warning'?c.warning:c.danger}]}>{t(status,tone==='healthy'?'سليم':tone==='warning'?'تحذير':'منطقة خطر')}</Text></View>)}</View>
 <View style={[s.alert,{backgroundColor:c.card,borderColor:c.danger}]}><View style={[s.alertIcon,{backgroundColor:c.danger+'20'}]}><Feather name="alert-triangle" size={18} color={c.danger}/></View><View style={{flex:1}}><Text style={[s.alertTitle,{color:c.foreground}]}>{t('Danger hotspot detected','تم اكتشاف بؤرة خطر')}</Text><Text style={[s.alertBody,{color:c.mutedForeground}]}>{t('Sector A-4 is showing severe stress · NDVI 0.18','القطاع A-4 يظهر إجهاداً شديداً · NDVI 0.18')}</Text></View></View>
 <Pressable testID="capture-sector-a4" onPress={()=>{Haptics.selectionAsync();router.push('/diagnosis')}} style={({pressed})=>[s.primaryButton,{backgroundColor:c.accent,opacity:pressed?.82:1}]}><Feather name="camera" size={19} color={c.accentForeground}/><Text style={[s.primaryButtonText,{color:c.accentForeground}]}>{t('Capture Sector A-4','التقط صورة للقطاع A-4')}</Text><Feather name={isArabic?'arrow-left':'arrow-right'} size={18} color={c.accentForeground}/></Pressable>
 <View style={[s.tip,{backgroundColor:c.soft}]}><Feather name="wifi-off" size={17} color={c.primary}/><Text style={[s.tipText,{color:c.secondaryForeground}]}>{t('Offline monitoring is active. Your latest satellite tile is cached on this device.','المراقبة دون اتصال مفعّلة. أحدث صورة للقمر الصناعي محفوظة على هذا الجهاز.')}</Text></View>
 </ScrollView></View>}
const s=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:22},eyebrow:{fontSize:11,fontFamily:'Inter_700Bold',letterSpacing:1.6,marginBottom:8},title:{fontSize:25,fontFamily:'Inter_700Bold',letterSpacing:-.6},actions:{flexDirection:'row',gap:8},iconButton:{width:40,height:40,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center'},lang:{fontFamily:'Inter_700Bold',fontSize:13},hero:{borderRadius:24,padding:22,flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:28},heroLabel:{fontSize:12,color:'#D5F0DD',fontFamily:'Inter_600SemiBold',letterSpacing:1},heroNumber:{fontSize:54,color:'#FFFFFF',fontFamily:'Inter_700Bold',letterSpacing:-2,marginTop:5},heroCaption:{fontSize:13,color:'#D5F0DD',fontFamily:'Inter_500Medium'},ring:{width:87,height:87,borderRadius:44,borderWidth:8,borderColor:'#67C391',alignItems:'center',justifyContent:'center'},ringText:{fontSize:14,color:'#FFFFFF',fontFamily:'Inter_700Bold'},ringSub:{fontSize:10,color:'#D5F0DD',marginTop:3,fontFamily:'Inter_500Medium'},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline',marginBottom:13},sectionTitle:{fontSize:19,fontFamily:'Inter_700Bold'},updated:{fontSize:11,fontFamily:'Inter_500Medium'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:20},sector:{width:'48%',minHeight:116,borderRadius:18,borderWidth:1,padding:15},sectorTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectorName:{fontSize:12,fontFamily:'Inter_600SemiBold'},dot:{width:8,height:8,borderRadius:4},ndvi:{fontSize:28,fontFamily:'Inter_700Bold',marginTop:13},status:{fontSize:12,fontFamily:'Inter_600SemiBold',marginTop:1},alert:{borderRadius:18,borderWidth:1,padding:15,flexDirection:'row',gap:12,marginBottom:14},alertIcon:{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center'},alertTitle:{fontFamily:'Inter_700Bold',fontSize:14,marginBottom:5},alertBody:{fontFamily:'Inter_400Regular',fontSize:12,lineHeight:18},primaryButton:{borderRadius:17,minHeight:54,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:20},primaryButtonText:{fontFamily:'Inter_700Bold',fontSize:14},tip:{borderRadius:16,padding:14,flexDirection:'row',gap:10,alignItems:'center'},tipText:{flex:1,fontFamily:'Inter_500Medium',fontSize:12,lineHeight:18}});